sudo: required
services: 
  - docker

install: travis_wait 30 mvn install

before_install:
  - docker build -t sagardokhale29/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sagardokhale29/react-test npm test -- --coverage

after_success:
  - docker build -t sagardokhale29/multi-client ./client
  - docker build -t sagardokhale29/multi-nginx ./nginx
  - docker build -t sagardokhale29/multi-server ./server
  - docker build -t sagardokhale29/multi-worker ./worker

  #log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push it to docker hub
  - docker push sagardokhale29/multi-client
  - docker push sagardokhale29/multi-nginx
  - docker push sagardokhale29/multi-server
  - docker push sagardokhale29/multi-worker