sudo: required
services: 
  - docker

before_install:
  - docker build -t sagardokhale29/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true sagardokhale29/react-test npm run test

after_success:
  - docker build -t sagardokhale29/multi-client ./client
  - docker build -t sagardokhale29/multi-nginx ./nginx
  - docker build -t sagardokhale29/multi-server ./server
  - docker build -t sagardokhale29/multi-worker ./worker

  #log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push it to docker hub
  - docker push sagardokhale29/multi-client
  - docker push sagardokhale29/multi-nginx
  - docker push sagardokhale29/multi-server
  - docker push sagardokhale29/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: elasticbeanstalk-us-east-2-727302975843
  bucket_path: docker_multi
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
